    

#% from local gems:   theme: jekyll-theme-tactile
#%fine till25.11.1 remote_theme: pages-themes/tactile@v0.2.0
remote_theme: pages-themes/tactile@v0.2.0
#%mistral.ail failed on remote_theme: cotes2020/jekyll-theme-chirpy
#% fails 2troubleshoot remote_theme: pages-themes/minimal@v0.2.0

sass:
  style: compressed
    #quiet_deps: true
    # silence_deprecations: [import]
#% GitHub Pages will: Build your Sass Include the theme Apply your overrides


    # minimal_mistakes_skin    : "aqua" #, "dark" # "air", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
        #%      css: "/assets/css/style.css"
#%# style.scss will be compiled to style.css stylesheet key tells GitHub Pages to use your compiled CSS

locale: "en-US"
title: Zrydys page 

description: Open Source zrydys tools 
url: "https://zrydys.github.io/"

# Site Author
author:
  name             : "WebProTime Jekyll Theme"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Lets Make A Blog."
  location         : "Earth"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:zrydys@gmail.
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://zrydys.github.io/"


github:
  public: true
  is_project_page: true
  repository_url: https://github.com/zrydys/zrydys.github.io
  owner_url: https://github.com/zrydys

mermaid: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag


0minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  #was skin: classic
  skin: auto 

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:
    - title: repository at GitHub
      icon: github
      url: "https://github.com/zrydys"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/zrydys"


